name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    timeout-minutes: 20
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
    steps:
      - name: Checkout repository
        # v4
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup uv
        # v6.4.3
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41
        with:
          python-version: '3.13'
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
            **/scripts/*.py
      - name: Install nfpm
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/actions/install-nfpm
      - name: Setup Bun
        if: matrix.os == 'ubuntu-latest'
        # v2.0.2
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
      - name: Check formatting
        if: matrix.os == 'ubuntu-latest'
        run: make check-fmt
        shell: bash
      - name: Run lint checks
        if: matrix.os == 'ubuntu-latest'
        run: make lint
        shell: bash
      - name: Run tests
        run: |
          uv sync --group dev
          uv run pytest
        env:
          PYTHONIOENCODING: utf-8
        shell: bash

  python-tests-windows:
    timeout-minutes: 20
    permissions:
      contents: read
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        # v4
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup uv
        # v6.4.3
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41
        with:
          python-version: '3.13'
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
            **/scripts/*.py
      - name: Run tests
        run: |
          uv sync --group dev
          uv run pytest
        env:
          PYTHONIOENCODING: utf-8
        shell: bash
